services:
  app:
    container_name: app
    build: ./app
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app-network
    restart: always

  database:
    container_name: database
    build: ./database
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:

volumes:
  database:
